services:
  nps-appen:
    image: ghcr.io/upheads-int/nps-appen/nps-appen:latest
    build: .
    volumes:
      - nps-data:/data
    environment:
      PORT: 3003
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      FROM_EMAIL: ${FROM_EMAIL}
      FROM_NAME: ${FROM_NAME}
      APP_URL: ${APP_URL}
    restart: unless-stopped

volumes:
  nps-data:

networks:
  default:
    name: asai-proj-nps-appen
